version: "3.7"
services:
  terraform-runner:
    image: hashicorp/terraform:light
    volumes:
      - ./terraform:/sqs-lambda-cloudsearch
      - ./elasticsearch-indexer-lambda:/lambda
    working_dir: /sqs-lambda-cloudsearch
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
