version: "3.7"
services:
  terraform-runner:
    image: hashicorp/terraform:light
    volumes:
      - ./terraform:/sqs-lambda-elasticsearch
      - ./elasticsearch-indexer-lambda:/lambda
    working_dir: /sqs-lambda-elasticsearch
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
  elasticsearch-indexer-lambda:
    image: lambci/lambda:python3.7
    volumes:
      - ./elasticsearch-indexer-lambda:/var/task
    command: elasticsearch_indexer_lambda.handler
    environment:
      - ES_HOST=elasticsearch
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    networks:
      - elastic
networks:
  elastic:
